apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-petstoreservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-petstoreservice
  template:
    metadata:
      labels:
        app: aks-petstoreservice
    spec:
      containers:
      - name: aks-petstorepetservice
        image: stundzepetstorecr.azurecr.io/petstoreservice:latest
        ports:
        - containerPort: 80
        env:
        - name: PETSTOREPETSERVICE_SERVER_PORT
          value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: aks-petstoreservice 
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: aks-petstorepetservice
